# Generated by Django 6.0.1 on 2026-02-01 17:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Дата и время создания аккаунта', verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Одноразовый токен для сброса пароля (обычно 40–64 символа)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, help_text='Время создания токена — для проверки срока действия', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения профиля', verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Студент', 'Student'), ('Учитель', 'Teacher'), ('Админ', 'Admin')], default='Студент', max_length=40),
        ),
    ]
