# Generated by Django 6.0.1 on 2026-02-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Одноразовый токен для сброса пароля (обычно 40–64 символа)', max_length=100, null=True, unique=True),
        ),
    ]
