# Generated by Django 6.0.1 on 2026-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_file_key_customuser_file_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
