"""
Django settings for edulife project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,.onrender.com"
    ).split(",")
]

# CORS: с каких origin разрешены запросы к API (фронт на другом порту/домене)
# Через запятую, без пробелов после запятой: http://localhost:5173,https://my-app.vercel.app
_CORS_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").strip()
if _CORS_ORIGINS:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _CORS_ORIGINS.split(",") if o.strip()]
else:
    # По умолчанию — типичные адреса локального фронта (Vite, CRA и т.д.)
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
    ]
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    #'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Installed apps
    'whitenoise.runserver_nostatic',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'storages',
    'drf_yasg',
    'corsheaders',
    # My apps
    'apps.users',
    'apps.courses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edulife.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edulife.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

JAZZMIN_SETTINGS = {
    "site_title": "EduLife Admin Panel",
    "site_header": "EduLife Admin Panel",
    "site_brand": "Admin Panel",
    "welcome_sign": "Welcome to the Admin Panel",
    "show_sidebar": True,
    "navigation_expanded": True,
}


# Database: DATABASE_URL (Railway etc.) or POSTGRES_* env, else local defaults
_db_default = {
    "ENGINE": os.getenv("DJANGO_DB_ENGINE"),
    "NAME": os.getenv("POSTGRES_DB"),
    "USER": os.getenv("POSTGRES_USER"),
    "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
    "HOST": os.getenv("POSTGRES_HOST"),
    "PORT": os.getenv("POSTGRES_PORT"),
}
if os.getenv("DATABASE_URL"):
    DATABASES = {"default": dj_database_url.config(default=os.getenv("DATABASE_URL"), conn_max_age=600)}
else:
    DATABASES = {"default": _db_default}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

STORAGES = {
    "default": {
        # Cloud object storage (Cloudflare R2 / any S3‑compatible)
        "BACKEND": "edulife.storage.R2Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 629145600
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

#
# Object storage configuration (Cloudflare R2 / S3‑compatible)
#
# For backward compatibility we still read MINIO_* if R2_* are not provided.
R2_ACCOUNT_ID=os.getenv('R2_ACCOUNT_ID')
R2_ENDPOINT = os.getenv("R2_ENDPOINT") 
R2_ACCESS_KEY = os.getenv("R2_ACCESS_KEY") 
R2_SECRET_KEY = os.getenv("R2_SECRET_KEY") 
R2_USE_SSL = (
    os.getenv("R2_USE_SSL")
    or os.getenv("MINIO_USE_SSL", "false")
).lower() in ("1", "true", "yes")
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
R2_REGION_NAME = os.getenv("R2_REGION_NAME") 
R2_ENDPOINT_URL = os.getenv(
    "R2_ENDPOINT_URL"
    # Example for Cloudflare R2 S3 API:
    #   https://<account-id>.r2.cloudflarestorage.com
    # or custom S3‑compatible endpoint.
    or os.getenv("MINIO_ENDPOINT_URL")
    or f"http{'s' if R2_USE_SSL else ''}://{R2_ENDPOINT}",
)


SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Введите только access token (без слова Bearer). В реальных запросах отправляйте заголовок: Authorization: Bearer <access_token>',
        }
    },
    'SECURITY_REQUIREMENTS': [{'Bearer': []}],
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

AUTH_USER_MODEL = 'users.CustomUser'


# SMTP Configuration 

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
PASSWORD_RESET_TOKEN_EXPIRY_SECONDS = 1800
