# Generated by Django 6.0.1 on 2026-01-28 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_submission_updated_at_alter_course_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gradebook',
            constraint=models.UniqueConstraint(fields=('student', 'task'), name='unique_final_grade_per_student_task'),
        ),
    ]
