# Generated by Django 6.0.1 on 2026-02-17 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_progresscount_is_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgressCount',
            new_name='CompletedTask',
        ),
    ]
