# Generated by Django 6.0.1 on 2026-01-28 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='minutes',
            new_name='duration_minutes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='Contains learning objectives, duration, tasks, prerequisites'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Lesson #1', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_to_module', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_to_course', to='courses.course'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_graded', models.BooleanField(default=False)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('passing_score', models.PositiveIntegerField(default=70)),
                ('task_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('link', 'Link')], default='video', max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='courses.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'task'), name='unique_submission_per_student_task')],
            },
        ),
    ]
