# Generated by Django 6.0.1 on 2026-01-28 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_taskcompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskcompletion',
            constraint=models.UniqueConstraint(fields=('student', 'task'), name='unique_completion_per_student_task'),
        ),
    ]
