# Generated by Django 6.0.1 on 2026-01-28 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_gradebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo link or external resource URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='file_content/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx', 'xlsx', 'zip', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
