# Generated by Django 6.0.1 on 2026-01-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_gradebook_unique_final_grade_per_student_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
