# Generated by Django 6.0.1 on 2026-01-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_taskcompletion_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcompletion',
            old_name='created_at',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='taskcompletion',
            old_name='completed',
            new_name='status',
        ),
    ]
