# Generated by Django 6.0.1 on 2026-01-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_created_at_taskcompletion_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prerequisites',
            new_name='short_description',
        ),
    ]
