# Generated by Django 6.0.1 on 2026-01-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_rename_prerequisites_course_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_published',
            new_name='published_time',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_to_module', to='courses.module'),
        ),
    ]
