# Generated by Django 6.0.1 on 2026-02-04 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_category_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='file_content/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'pptx', 'ppt', 'xlsx', 'xls', 'zip', 'txt', 'rtf', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
