# Generated by Django 6.0.1 on 2026-02-07 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'pptx', 'ppt', 'xlsx', 'xls', 'zip', 'txt', 'rtf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='task',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link to YouTube video or external resource URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='passing_score',
            field=models.PositiveIntegerField(blank=True, default=70, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
