# Generated by Django 6.0.1 on 2026-02-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_submission_student_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='lesson',
            new_name='module',
        ),
    ]
