# Generated by Django 6.0.1 on 2026-02-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_rename_lesson_task_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='passing_score',
        ),
        migrations.AddField(
            model_name='task',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 attempt'), (3, '3 attempts')], default=1, null=True),
        ),
    ]
