# Generated by Django 6.0.1 on 2026-02-09 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_task_passing_score_task_max_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gradebook',
            name='unique_final_grade_per_student_task',
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_submission_per_student_task',
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'Студент'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='task',
        ),
        migrations.DeleteModel(
            name='GradeBook',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
