# Generated by Django 6.0.1 on 2026-02-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_gradebook_unique_final_grade_per_student_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_graded',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='weight',
        ),
    ]
