# Generated by Django 6.0.1 on 2026-02-09 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_task_is_graded_remove_task_max_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCompletion',
            new_name='ProgressCount',
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
