# Generated by assistant to align model and DB
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_rename_taskcompletion_progresscount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='published_time',
            new_name='creation_time',
        ),
    ]
