# Generated by Django 6.0.1 on 2026-02-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_rename_published_time_to_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
