# Generated by Django 6.0.1 on 2026-02-10 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 8, 24, 47, 159764, tzinfo=datetime.timezone.utc)),
        ),
    ]
