# Generated by Django 6.0.1 on 2026-02-10 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 8, 26, 10, 543407, tzinfo=datetime.timezone.utc)),
        ),
    ]
