# Generated by Django 6.0.1 on 2026-02-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='external_url',
            field=models.URLField(blank=True, help_text='External resource URL', max_length=500, null=True),
        ),
    ]
