# Generated by Django 6.0.1 on 2026-02-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_remove_task_status_alter_task_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
