# Generated by Django 6.0.1 on 2026-02-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_course_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
