# Generated by Django 6.0.1 on 2026-02-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_course_original_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file_key',
        ),
        migrations.RemoveField(
            model_name='course',
            name='file_mime_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='file_size',
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_to_course', to='courses.course'),
        ),
    ]
