# Generated by Django 6.0.1 on 2026-02-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_remove_course_file_key_remove_course_file_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='file_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
